LOCK TABLES `data_platform_currency_currency_text_data` WRITE;

INSERT INTO `data_platform_currency_currency_text_data` (`Currency`, `Language`, `CurrencyName`,`CurrencyLongName`)
VALUES
    ('AED', 'JA', 'ディルハム', 'アラブ首長国連邦ディルハム'),
    ('AFN', 'JA', 'アフガニ', 'アフガニ'),
    ('ALL', 'JA', 'Lek', 'Albanian Lek'),
    ('AMD', 'JA', 'Dram', 'Armenian Dram'),
    ('ANG', 'JA', 'W.Ind. ギルダー', '西インド連邦ギルダー'),
    ('AOA', 'JA', 'クワンザ', 'アンゴラクワンザ'),
    ('ARS', 'JA', 'Arg. ペソ', 'アルゼンチンペソ'),
    ('AUD', 'JA', 'Australia ドル', 'オーストラリアドル'),
    ('AWG', 'JA', 'Aruban Florin', 'アルバニアフロリン'),
    ('AZN', 'JA', 'Manat', 'アゼルバイジャンマナト'),
    ('BAM', 'JA', '兌換マルク', 'ボスニアヘルツェゴビナ兌換マルク'),
    ('BBD', 'JA', 'ドル', 'バルバドスドル'),
    ('BDT', 'JA', 'Taka', 'Bangladesh Taka'),
    ('BGN', 'JA', 'Lev', 'ブルガリアレフ'),
    ('BHD', 'JA', 'ディナール', 'バーレーンディナール'),
    ('BIF', 'JA', 'Burundi フラン', 'ブルンディフラン'),
    ('BMD', 'JA', 'バミューダドル', 'バミューダドル'),
    ('BND', 'JA', 'ドル', 'ブルネイドル'),
    ('BOB', 'JA', 'ボリビアーノ', 'ボリビアーノ'),
    ('BRL', 'JA', 'レアル', 'ブラジルレアル'),
    ('BSD', 'JA', 'ドル', 'バハマドル'),
    ('BTN', 'JA', 'Ngultrum', 'ブータン Ngultrum'),
    ('BWP', 'JA', 'プラ', 'ボツワナプラ'),
    ('BYN', 'JA', 'Bela. Ruble', 'ベラルーシルーブル '),
    ('BYR', 'JA', 'ルーブル', 'ベロルシアルーブル'),
    ('BZD', 'JA', 'ドル', 'Belize dollars'),
    ('CAD', 'JA', 'カナダドル', 'カナダドル'),
    ('CDF', 'JA', 'テストデータ', 'コンゴフラン'),
    ('XPF', 'JA', 'Fr.フラン (Pac)', 'フランスフラン (太平洋諸島)'),
    ('CHF', 'JA', 'スイスフラン', 'スイスフラン'),
    ('CLP', 'JA', 'ペソ', 'チリペソ'),
    ('CNY', 'JA', '中国元', '中国元'),
    ('COP', 'JA', 'ペソ', 'コロンビアペソ'),
    ('CRC', 'JA', 'Cost.Ricaコロン', 'コスタリカコロン'),
    ('CUC', 'JA', 'ペソ兌換', 'ペソ兌換'),
    ('CUP', 'JA', 'キューバペソ', 'キューバペソ'),
    ('CVE', 'JA', 'エスクード', 'カボヴェルデエスクード'),
    ('CZK', 'JA', 'クローナ', 'チェコクローナ'),
    ('DJF', 'JA', 'ジブティフラン', 'ジブティフラン'),
    ('DKK', 'JA', 'Danish Krone', 'デンマーククローネ'),
    ('DOP', 'JA', 'ドミニカペソ', 'ドミニカペソ'),
    ('DZD', 'JA', 'ディナール', 'アルジェリアディナール'),
    ('EGP', 'JA', 'ポンド', 'エジプトポンド'),
    ('ERN', 'JA', 'ナフカ', 'エリトリアナフカ'),
    ('ETB', 'JA', 'ビル', 'エチオピアビル'),
    ('EUR', 'JA', 'ユーロ', 'EMU 通貨 (ユーロ)'),
    ('FJD', 'JA', 'ドル', 'フィージードル'),
    ('FKP', 'JA', 'Falkland ポンド', 'フォークランドポンド'),
    ('GBP', 'JA', 'ポンド', 'イギリスポンド'),
    ('GEL', 'JA', 'ラリ', 'グルジアラリ'),
    ('GHS', 'JA', 'Cedi', 'Ghanian Cedi'),
    ('GIP', 'JA', 'ジブラルタルポ', 'ジブラルタルポンド'),
    ('GMD', 'JA', 'Dalasi', 'Gambian Dalasi'),
    ('GNF', 'JA', 'ギニアフラン', 'ギニアフラン'),
    ('GTQ', 'JA', 'ケツァール', 'グアテマラケツァール'),
    ('GYD', 'JA', 'ガイアナドル', 'ガイアナドル'),
    ('HKD', 'JA', '香港ドル', '香港ドル'),
    ('HNL', 'JA', 'Lempira', 'Honduran Lempira'),
    ('HRK', 'JA', 'Kuna', 'クロアチア Kuna'),
    ('HTG', 'JA', 'Gourde', 'Haitian Gourde'),
    ('HUF', 'JA', 'フォーリント', 'ハンガリフォーリント'),
    ('IDR', 'JA', 'ルピア', 'インドネシアルピア'),
    ('ILS', 'JA', 'Scheckel', 'Israeli Scheckel'),
    ('INR', 'JA', 'ルピー', 'インドルピー'),
    ('IQD', 'JA', 'ディナール', 'イラクディナール'),
    ('IRR', 'JA', 'リヤル', 'イランリヤル'),
    ('ISK', 'JA', 'クローナ', 'アイスランドクローナ'),
    ('JMD', 'JA', 'ジャマイカドル', 'ジャマイカドル'),
    ('JOD', 'JA', 'Jordanian Dinar', 'ヨルダンディナール'),
    ('JPY', 'JA', '円', '日本円'),
    ('KES', 'JA', 'シリング', 'ケニヤシリング'),
    ('KGS', 'JA', 'Som', 'キルギスタン Som'),
    ('KHR', 'JA', 'Riel', 'Cambodian Riel'),
    ('KMF', 'JA', 'Comoros Franc', 'Comoros Franc'),
    ('KPW', 'JA', 'N. Korean Won', 'North Korean Won'),
    ('KRW', 'JA', 'S.Korean Won', 'South Korean Won'),
    ('KWD', 'JA', 'ディナール', 'クウェートディナール'),
    ('KYD', 'JA', 'ケーマンドル', 'ケーマンドル'),
    ('KZT', 'JA', 'テンゲ', 'カザフスタンテンゲ'),
    ('LAK', 'JA', 'Kip', 'Laotian Kip'),
    ('LBP', 'JA', 'レバノンポンド', 'レバノンポンド'),
    ('LKR', 'JA', 'Sri Lankaルピー', 'スリランカルピー'),
    ('LRD', 'JA', 'リベリアドル', 'リベリアドル'),
    ('LSL', 'JA', 'Loti', 'Lesotho Loti'),
    ('LTL', 'JA', 'Lita', 'Lithuanian Lita'),
    ('LVL', 'JA', 'ラート', 'ラトビアラート'),
    ('LYD', 'JA', 'Libyan Dinar', 'リビアディナール'),
    ('MAD', 'JA', 'ディルハム', 'Moroccan Dirham'),
    ('MDL', 'JA', 'レイ', 'モルダビアレイ'),
    ('MGA', 'JA', 'Madagasc.Ariary', 'マダガスカルアリアリ'),
    ('MKD', 'JA', 'ディナリ', 'マケドニアディナリ'),
    ('MMK', 'JA', 'チャット', 'ミャンマーチャット'),
    ('MNT', 'JA', 'トゥグリク', 'モンゴルトゥグリク'),
    ('MOP', 'JA', 'パタカ', 'マカオパタカ'),
    ('MRO', 'JA', 'Ouguiya', 'Mauritanian Ouguiya'),
    ('MRU', 'JA', 'Ouguiya', 'Mauritanian Ouguiya'),
    ('MUR', 'JA', 'ルピー', 'モーリタニアルピー'),
    ('MVR', 'JA', 'Rufiyaa', 'Maldive Rufiyaa'),
    ('MWK', 'JA', 'Malawi Kwacha', 'Malawi Kwacha'),
    ('MXN', 'JA', 'ペソ', 'メキシコペソ'),
    ('MYR', 'JA', 'リングギット', 'マレーシアリンゲット'),
    ('MZN', 'JA', 'Metical', 'モザンビークメティカル'),
    ('NAD', 'JA', 'ナミビアドル', 'ナミビアドル'),
    ('NGN', 'JA', 'Naira', 'Nigerian Naira'),
    ('NIO', 'JA', 'コルドバオロ', 'ニカラグアコルドバオロ'),
    ('NOK', 'JA', 'Norwegian Krone', 'ノルウェークローネ'),
    ('NPR', 'JA', 'ルピー', 'ネパールルピー'),
    ('NZD', 'JA', 'N.Zeal. ドル', 'ニュージーランドドル'),
    ('OMR', 'JA', 'オーマンリアル', 'オーマンリアル'),
    ('PAB', 'JA', 'バルボア', 'パナマバルボア'),
    ('PEN', 'JA', 'New Sol', 'ペルー New Sol'),
    ('PGK', 'JA', 'Kina', 'Papua New Guinea Kina'),
    ('PHP', 'JA', 'ペソ', 'フィリピンペソ'),
    ('PKR', 'JA', 'ルピー', 'パキスタンルピー'),
    ('PLN', 'JA', 'Zloty', 'ポーランド Zloty '),
    ('PYG', 'JA', 'Guarani', 'Paraguayan Guarani'),
    ('QAR', 'JA', 'リヤル', 'カタールリヤル'),
    ('CNY', 'JA', '人民元', '人民元'),
    ('RON', 'JA', 'レイ', 'ルーマニアレイ'),
    ('RSD', 'JA', 'セルビア Dinar', 'セルビアディナール'),
    ('RUB', 'JA', 'ルーブル', 'ロシアルーブル'),
    ('RWF', 'JA', 'ギニアフラン', 'ルワンダフラン'),
    ('SAR', 'JA', 'リヤル', 'サウジリヤル'),
    ('SBD', 'JA', 'Sol.Isl. ドル', 'ソロモン群島ドル'),
    ('SCR', 'JA', 'ルピー', 'Seychelles Rupee'),
    ('SDG', 'JA', 'ポンド', 'スーダンポンド'),
    ('SEK', 'JA', 'Swedish Krona', 'スウェーデンクローネ'),
    ('SGD', 'JA', 'Sing.dollars', 'シンガポールドル'),
    ('SHP', 'JA', 'St.Helena Pound', 'セントヘレナポンド'),
    ('SLL', 'JA', 'レオネ', 'シエラレオネレオネ'),
    ('SOS', 'JA', 'シリング', 'ソマリアシリング'),
    ('SRD', 'JA', 'スリナムドル', 'スリナムドル'),
    ('SSP', 'JA', 'ポンド', '南スーダンポンド'),
    ('STD', 'JA', 'Dobra', 'Sao Tome / Principe Dobra'),
    ('SVC', 'JA', 'コロン', 'エルサルバドルコロン'),
    ('SYP', 'JA', 'シリアポンド', 'シリアポンド'),
    ('SZL', 'JA', 'Lilangeni', 'Swaziland Lilangeni'),
    ('THB', 'JA', 'バーツ', 'タイバーツ'),
    ('TJS', 'JA', 'ソモニ', 'タジクソモニ'),
    ('TMT', 'JA', 'Manat', 'Turkmenistani Manat'),
    ('TND', 'JA', 'ディナール', 'チュニジアディナール'),
    ('TOP', 'JA', 'Paanga', 'TonganPaanga'),
    ('TPE', 'JA', 'Timor Escudo', 'チモールエスクード --> USD'),
    ('TRY', 'JA', 'リラ', 'トルコリラ'),
    ('TTD', 'JA', 'T.+ T. Dollar', 'Trinidad and Tobago Dollar'),
    ('TWD', 'JA', 'ドル', '新台湾ドル'),
    ('TZS', 'JA', 'シリング', 'タンザニアシリング'),
    ('UAH', 'JA', 'Hryvnia', 'Ukrainian Hryvnia'),
    ('UGX', 'JA', 'シリング', 'ウガンダシリング'),
    ('USD', 'JA', 'US ドル', 'アメリカドル'),
    ('UYU', 'JA', 'ペソ', 'ウルグアイペソ'),
    ('UZS', 'JA', '合計', 'ウズベキスタンスム'),
    ('VEF', 'JA', 'Bolivar fuerte', 'ベネズエラボリバルフエルテ'),
    ('VES', 'JA', 'Bolivar fuerte', 'ベネズエラボリバルフエルテ'),
    ('VND', 'JA', 'Dong', 'Vietnamese Dong'),
    ('VUV', 'JA', 'Vatu', 'Vanuatu Vatu'),
    ('WST', 'JA', 'Tala', 'Samoan Tala'),
    ('XAF', 'JA', 'CFA Franc BEAC', 'ガボン CFA フラン BEAC'),
    ('XCD', 'JA', 'ドル', '東カリブドル'),
    ('XEU', 'JA', 'E.C.U.', 'ヨーロッパ通貨単位 (E.C.U.)'),
    ('XOF', 'JA', 'CFA Franc BCEAO', 'ベニン CFA フラン BCEAO'),
    ('XPF', 'JA', 'ギニアフラン', 'CFP フラン'),
    ('YER', 'JA', 'Yemeni Ryal', 'Yemeni Ryal'),
    ('ZAR', 'JA', 'Rand', '南アフリカランド'),
    ('ZMW', 'JA', 'Kwacha', 'ザンビアクワチャ '),
    ('ZWL', 'JA', 'ジンバブエドル', 'ジンバブエドル ');
UNLOCK TABLES;
